# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2322e6f5c3329af9254423ba933dbbb04c3d453aad59afee6dbf6245fe3ac46e2259fcea3a134daa52d24b9c491b371053cdaa81ca3f4356f580e7170b605301

test:
  secret_key_base: 46df6369887a60cc8d0e43f55a02c5836e4150a2bb885dbc521b9a67deb392d77c332fa3b53d2a475e13ca3a97b8d7f7bd4333bc9c3853a24243625d7f396c1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
